import Link from "next/link";import Image from "next/image";import {getSiteSettings} from "@/lib/queries/siteSettings";import {getCurrentUser} from "@/lib/auth/userSession";import {logoutUser} from "@/app/(site)/login/actions";import MobileNav from "./MobileNav";import SearchBar from "./SearchBar";import HideOnHome from "./HideOnHome";
const NAV=[{href:"/",label:"Home"},{href:"/properties",label:"Properties"},{href:"/auctions",label:"Auctions"},{href:"/banks",label:"Banks"},{href:"/cities",label:"Cities"},{href:"/how-it-works",label:"How It Works"},{href:"/blog",label:"Insights"}];
export default async function Header(){const [settings,user]=await Promise.all([getSiteSettings(),getCurrentUser()]);return <header className="sticky top-0 z-50 bg-white/95 backdrop-blur border-b border-brand-border">
 <div className="bg-brand text-white"><div className="max-w-[1240px] mx-auto px-5 py-2 flex items-center justify-between text-[11px]"><div className="flex gap-5"><a href={`tel:${settings.phone.replace(/\s/g,"")}`}>{settings.phone}</a><a className="hidden sm:inline text-white/75" href={`mailto:${settings.generalEmail}`}>{settings.generalEmail}</a></div><span className="hidden md:block text-white/70">{settings.workingHours}</span></div></div>
 <div className="max-w-[1240px] mx-auto px-5 py-3.5 flex items-center gap-6"><Link href="/" className="shrink-0"><Image src="/brand/logo.png" alt="BankAuction.co" width={168} height={66} priority className="h-11 w-auto"/></Link>
 <nav className="hidden lg:flex items-center gap-5 text-[13px] font-semibold text-slate-700">{NAV.map(n=><Link key={n.href} href={n.href} className="hover:text-brand transition-colors">{n.label}</Link>)}</nav>
 <div className="hidden xl:block flex-1 max-w-sm ml-auto"><HideOnHome><SearchBar/></HideOnHome></div>
 {user?<div className="hidden md:flex items-center gap-3 ml-auto text-xs"><span className="font-semibold">Hi, {user.name?.split(" ")[0]??"there"}</span><form action={logoutUser}><button className="text-brand-muted hover:text-brand">Sign out</button></form></div>:<Link href="/login" className="hidden md:flex items-center gap-2 text-xs font-semibold text-brand border border-brand-border px-3 py-2 rounded-lg">Account</Link>}
 <MobileNav navItems={NAV} isLoggedIn={!!user} logoutAction={logoutUser}/></div>
 </header>}
