import Link from "next/link";import {prisma} from "@/lib/db/prisma";import PropertyCarousel from "@/components/PropertyCarousel";import {toPropertyCardData} from "@/lib/queries/listProperties";import SearchBar from "@/components/SearchBar";import AuctionCountdownTable,{CountdownRow} from "@/components/AuctionCountdownTable";import {PRIORITY_CITIES} from "@/lib/constants";
export const revalidate=120;
const TYPES=[["RESIDENTIAL","Residential","Homes, flats & apartments","⌂"],["COMMERCIAL","Commercial","Shops, offices & spaces","▥"],["INDUSTRIAL","Industrial","Factories & warehouses","▦"],["LAND_PLOT","Land & Plot","Plots & open land","⌗"],["AGRICULTURAL","Agricultural","Farms & agricultural land","♧"],["VEHICLE","Vehicles","Cars, trucks & more","▱"]];
export default async function Home(){const [active,banks,upcoming,featured,cityGroups,topBanks,countdowns]=await Promise.all([
 prisma.property.count({where:{status:"PUBLISHED"}}),prisma.bank.count({where:{auctions:{some:{property:{status:"PUBLISHED"}}}}}),prisma.auction.count({where:{status:{in:["UPCOMING","LIVE","AUCTION_TODAY"]},property:{status:"PUBLISHED"}}}),
 prisma.property.findMany({where:{status:"PUBLISHED",auctions:{some:{status:{in:["UPCOMING","LIVE","AUCTION_TODAY"]}}}},orderBy:{createdAt:"desc"},take:12,include:{auctions:{include:{bank:true},orderBy:{createdAt:"desc"},take:1}}}),
 prisma.property.groupBy({by:["addressText"],where:{status:"PUBLISHED",addressText:{in:PRIORITY_CITIES}},_count:true}),
 prisma.bank.findMany({include:{_count:{select:{auctions:{where:{property:{status:"PUBLISHED"}}}}},orderBy:{auctions:{_count:"desc"}},take:6}),
 prisma.auction.findMany({where:{status:{in:["UPCOMING","LIVE","AUCTION_TODAY"]},property:{status:"PUBLISHED"}},orderBy:{auctionStart:"asc"},take:40,include:{bank:true,property:true}})
]);const cityMap=new Map(cityGroups.map(g=>[g.addressText,g._count]));const seen=new Set<string>();const rows:CountdownRow[]=[];for(const a of countdowns){if(seen.has(a.propertyId))continue;seen.add(a.propertyId);rows.push({id:a.id,slug:a.property.slug,title:a.property.title,bankName:a.bank?.name??null,location:a.property.addressText,category:a.property.category,auctionStart:a.auctionStart?.toISOString()??null});}
return <main>
<section className="bg-brand overflow-hidden"><div className="ba-section py-16 lg:py-20"><div className="max-w-4xl mx-auto text-center"><div className="ba-kicker mb-3">India's bank auction discovery platform</div><h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-[-.04em] leading-[1.05] text-white">Find bank auction properties <span className="text-gold">with clarity.</span></h1><p className="mt-5 text-sm sm:text-base leading-7 text-white/70 max-w-2xl mx-auto">Search source-backed auction listings across India with reserve price, auction dates, bank details and official documents.</p><div className="max-w-3xl mx-auto mt-8"><SearchBar size="lg"/></div><div className="mt-5 flex flex-wrap justify-center gap-3"><Link href="/properties" className="ba-btn ba-btn-gold px-5 py-3 text-sm">Explore properties</Link><Link href="/how-it-works" className="ba-btn border border-white/20 text-white px-5 py-3 text-sm">How it works</Link></div></div></div></section>
<section className="ba-section -mt-8 relative z-10"><div className="grid sm:grid-cols-3 gap-3">{[[active,"Active listings","Live published property records"],[banks,"Banks covered","Institutions with listings"],[upcoming,"Upcoming auctions","Upcoming & live auction events"]].map(([v,l,d])=><div key={String(l)} className="ba-card p-5"><div className="text-2xl font-extrabold text-brand">{v}</div><div className="mt-1 text-sm font-semibold">{l}</div><div className="mt-1 text-xs text-brand-muted">{d}</div></div>)}</div></section>
<section className="ba-section py-14"><div className="flex items-end justify-between mb-6"><div><div className="ba-kicker">Fresh listings</div><h2 className="text-2xl font-extrabold text-brand">Latest bank auction properties</h2></div><Link href="/properties" className="text-sm font-bold text-brand">View all →</Link></div><PropertyCarousel properties={featured.map(toPropertyCardData)}/></section>
<section className="bg-white border-y border-brand-border"><div className="ba-section py-14"><div className="mb-6"><div className="ba-kicker">Browse</div><h2 className="text-2xl font-extrabold text-brand">Find by property type</h2></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">{TYPES.map(([c,l,d,icon])=><Link key={c} href={`/property-type/${String(c).toLowerCase()}`} className="ba-card p-5 hover:border-brand hover:shadow-md transition-all"><div className="w-11 h-11 rounded-xl bg-brand-bg text-brand grid place-items-center text-xl mb-4">{icon}</div><div className="font-extrabold text-sm">{l}</div><div className="text-[11px] text-brand-muted mt-1 leading-5">{d}</div></Link>)}</div></div></section>
<section className="ba-section py-14"><div className="flex items-end justify-between mb-6"><div><div className="ba-kicker">Auction calendar</div><h2 className="text-2xl font-extrabold text-brand">Upcoming auctions</h2></div><Link href="/auctions" className="text-sm font-bold text-brand">View all →</Link></div><div className="ba-card overflow-hidden"><AuctionCountdownTable rows={rows}/></div></section>
<section className="ba-section py-14"><div className="flex items-end justify-between mb-6"><div><div className="ba-kicker">Explore India</div><h2 className="text-2xl font-extrabold text-brand">Popular auction locations</h2></div><Link href="/cities" className="text-sm font-bold text-brand">All cities →</Link></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">{PRIORITY_CITIES.map(city=><Link key={city} href={`/properties?q=${encodeURIComponent(city)}`} className="ba-card p-4 hover:border-brand transition-colors"><div className="font-bold text-sm">{city}</div><div className="text-xs text-brand-muted mt-1">{cityMap.get(city)??0} listings</div></Link>)}</div></section>
<section className="bg-brand"><div className="ba-section py-14"><div className="grid lg:grid-cols-[1fr_auto] gap-8 items-center"><div><div className="ba-kicker">Source-backed marketplace</div><h2 className="text-3xl font-extrabold text-white">Every listing stays connected to its auction source.</h2><p className="text-sm text-white/65 mt-3 max-w-2xl">Reserve price, EMD, auction schedule and official notice links are kept with the listing so users can verify the details before bidding.</p></div><Link href="/properties" className="ba-btn ba-btn-gold px-6 py-3 text-sm">Browse auctions →</Link></div></div></section>
</main>}
